# Generated by Django 2.0.6 on 2019-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.FileField(blank=True, upload_to='settings.MEDIA_ROOT'),
        ),
    ]
